min_severity: medium              # ignore "low" by default
cooldown_minutes: 30              # don't repeat the same action-target within this window
auto_cleanup_on_start: true       # remove expired containment rules on each run

never_block_cidrs:
  - "127.0.0.0/8"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"
  - "::1/128"

playbooks:
  # 1) SQL injection → block IP (24h) + notify Slack + ticket
  - name: sqli_containment
    filter:
      include_rules: ["SQLI_IN_URL"]
      min_severity: high
    actions:
      - type: block_ip
        ttl_minutes: 1440            # 24 hours
      - type: slack_notify
        route: slack-high            # reuse Day 3 "slack-high" route
      - type: write_ticket
        path: "tickets/containment.md"
        template_path: "templates/ticket_default.md.j2"

  # 2) Sensitive admin path → notify + ticket (no block)
  - name: sensitive_path_watch
    filter:
      include_rules: ["SENSITIVE_PATH"]
      min_severity: medium
    actions:
      - type: slack_notify
        route: slack-high
      - type: write_ticket
        path: "tickets/sensitive-path.md"
        template_path: "templates/ticket_default.md.j2"
